name = "serverless-qrcode-hub"
main = "index.js"
compatibility_date = "2025-03-15"

kv_namespaces = [
    # 注意：将下面的 id 替换为你自己拷贝的 KV 命名空间 id 才能正常使用！
    { binding = "KV_BINDING", id = "a68f3f09b7f14ba3b99dec5f33927545" },
]

[env.dev]
kv_namespaces = [
    { binding = "KV_BINDING", id = "24c3411876a34ba49e92d7ccb39fb81a" },
]

[env.dev.triggers]
crons = ["*/10 * * * * *"]

[triggers]
crons = ["0 2 */1 * *"]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability.logs]
enabled = true
